export const h1Style = 'mb-6 text-6xl font-black text-yellow-300'
export const h3Style = 'text-xl font-semibold my-6 text-yellow-300'
export const linkStyles = 'hover:text-blue-400 focus:text-blue-400 transition-all'
export const backLinkStyle = 'py-2 px-4 text-xs bg-slate-900 border-solid border-2 border-transparent rounded-md hover:bg-blue-950 hover:border-blue-600 transition-all'
export const navTitleStyle = 'ml-4 flex flex-.5 text-2xl font-bold text-yellow-300'
export const mainWidthStyles = 'w-11/12 md:w-9/12 lg:w-7/12'